#!/usr/bin/python3
#!-*- coding: utf8 -*-

''' Documentation '''

import sys
import time
import os
import universe


def print_header():
    print('\n')
    print('##########################################################')
    print('#    Automated generator to RAMAM maximum displacement   #')
    print('# Usage:                                                 #')
    print('# python3 main.py <input file> <nsteps>                  #')
    print('#                                                        #')
    print('# We are currently only supporting the TurboMole output. #')
    print('##########################################################')
    print('\n')

    return None


def read_input(input_name):
    ''' Documentation '''
    if not os.path.isfile(input_name):
        return False
    return True


def read_eq_coord(file_name):
    ''' Documentation '''
    file = open(file_name, 'r' )
    inp=file.readlines()
    file.close()

    for lineN in range(len(inp)):

        molecule=[]
        if "atomic coordinates" in inp[lineN]:
            # end=False
            count=1
            while (inp[lineN+count][:-1] != " "):
                line=inp[lineN+count][:-1].split()

                atom=universe.atom(name = line[3],
                                    x = line[0],
                                    y = line[1],
                                    z = line[2])

                molecule.append(atom)
                count+=1
            break
    return molecule

def read_displacements(file_name,molecule):
    ''' Documentation '''
    file = open(file_name, 'r' )
    inp=file.readlines()
    file.close()

    for lineN in range(len(inp)):
        if "NORMAL MODES and VIBRATIONAL FREQUENCIES" in inp[lineN]:
            # end=False
            count=12 #skipping the frequencies documentation
            while (not "time elapsed for vibrational analysis" in inp[lineN+count][:-1]):
                if "RAMAN" in inp[lineN+count][:-1]:
                    count+=2 #Jumping the empty line before the RAMAN statment
                    for atom in molecule:
                        line = inp[lineN+count][:-1].split()
                        for disp in range(3,len(line)):
                            atom.set_Dx(line[disp])
                        count+=1
                        
                        line = inp[lineN+count][:-1].split()
                        for disp in range(1,len(line)):
                            atom.set_Dy(line[disp])
                        count+=1
                        
                        line = inp[lineN+count][:-1].split()
                        for disp in range(1,len(line)):
                            atom.set_Dz(line[disp])
                        count+=1
                    # break
                count+=1
                line=inp[lineN+count][:-1].split()
    return None


def write_xyz(input_name, molecule, nsteps):
    ''' Documentation '''
    dispCount=0
    stepCount=0
    os.system("mkdir -p {0}".format(input_name))
    for disp in range(len(molecule[0].get_Dx())):
        dispName="disp_{0}".format(dispCount+1)
        os.system("mkdir -p {0}/{1}".format(input_name, dispName))
        for step in range(nsteps):
            stepName="step_{0}".format(stepCount)
            out = open("{0}/{1}/{2}.xyz".format(input_name, dispName, stepName),'w')
            out.write("\n")
            out.write("File automated generated by a cool script. :)\n")
            out.write("Python rules\n")
            out.write("\n")
            out.write("{0}\n".format(len(molecule)))
            out.write("Step number {0} of the frequencie mode number {1} discretization\n".format(stepCount, dispCount))
            for atom in molecule:
                xCoord=float(atom.get_x()) + float(atom.get_Dx()[dispCount])*(stepCount/nsteps)
                yCoord=float(atom.get_y()) + float(atom.get_Dy()[dispCount])*(stepCount/nsteps)
                zCoord=float(atom.get_z()) + float(atom.get_Dz()[dispCount])*(stepCount/nsteps)
                out.write("{0:5s} {1:12.5f} {2:12.5f} {3:12.5f}\n".format(atom.get_name(),
                                                    float(xCoord),
                                                    float(yCoord),
                                                    float(zCoord)))
            out.close()
            stepCount+=1
        dispCount+=1

    return None

def main():
    startTime=time.time()
    ''' Documentation '''
    run_dir = os.path.dirname(__file__)
    print_header()

    if len(sys.argv) != 3:
        print("\nInsuficient parameters\n")
        exit()

    input_file=sys.argv[1]
    if not read_input(input_file):
        print("\nCheck your input file name!!\n")
        exit()

    nsteps=sys.argv[2]
    try:
        nsteps=int(nsteps)  
    except ValueError:
        print("\nnsteps should be an integer\n")
        exit()

    molecule = read_eq_coord(input_file)

    read_displacements(input_file,molecule)
    write_xyz(input_file[:-4], molecule,nsteps)

    print("The run took: {0} seconds".format(time.time()-startTime))
